services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/var/www/html
    depends_on:
      - mysql
      - mongodb
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=task_management
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=task_logs

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: task_management
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: